apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: vault-backend-test

spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200

      path: "kv/org"

      version: "v2"

      auth:
        tokenSecretRef:
          name: vault-token
          namespace: vault
          key: token