apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:

  name: postgres-external-secretss

  namespace: database



spec:

  refreshInterval: 1m



  secretStoreRef:

    name: vault-backend-test

    kind: ClusterSecretStore



  target:

    name: database-secretss

    creationPolicy: Owner



  data:

    - secretKey: DATABASE_PASSWORD

      remoteRef:

        key: prod

        property: DATABASE_PASSWORD



    - secretKey: DOCKER_HUB_USERNAME

      remoteRef:

        key: prod

        property: DOCKER_HUB_USERNAME



    - secretKey: DOCKER_HUB_PASSWORD

      remoteRef:

        key: prod

        property: DOCKER_HUB_PASSWORD