

services:
  db:
    image: postgres:17
    container_name: order-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet


  order_service:
    build: .
    container_name: order_service_dist
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Boss2000
      DATABASE_NAME: distributed
      APP_ENV: production
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: