apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-secret-prod
  namespace: default

spec:
  refreshInterval: 1m

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: order-service-secrets
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: prod
        property: DATABASE_PASSWORD