apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configmap
  namespace: {{.Values.namespace.app}}
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: distributed
  DATABASE_USER: postgres