apiVersion: v1
kind: Pod

metadata:
  name: backup-inspector
  namespace: order-service

spec:
  containers:
  - name: inspector
    image: busybox
    command:
      - sleep
      - "3600"

    volumeMounts:
    - name: backup-storage
      mountPath: /backup

  volumes:
  - name: backup-storage
    persistentVolumeClaim:
      claimName: postgres-backup-pvc