apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: observability

spec:
  selector:
    matchLabels:
      app: promtail

  template:
    metadata:
      labels:
        app: promtail

    spec:
      serviceAccountName: promtail

      containers:
        - name: promtail
          image: grafana/promtail:2.9.8

          args:
            - -config.file=/etc/promtail/promtail.yml

          volumeMounts:

            # config
            - name: config
              mountPath: /etc/promtail

            # position file
            - name: run
              mountPath: /run/promtail

            # system logs
            - name: varlog
              mountPath: /var/log

            # docker logs (important if using docker runtime)
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true

      volumes:

        - name: config
          configMap:
            name: promtail-config

        - name: run
          hostPath:
            path: /run/promtail

        - name: varlog
          hostPath:
            path: /var/log

        - name: containers
          hostPath:
            path: /var/lib/docker/containers