apiVersion: v1

kind: Service

metadata:

  name: order-service-endpoint

  namespace: order-service

  labels:

    app.kubernetes.io/name: order-service-api

spec:

  selector:

    app.kubernetes.io/name: order-service-api

  ports:

    - name: metrics

      port: 90

      targetPort: 8000

  type: ClusterIP