"""add item_count to order_read_model

Revision ID: 021bb0fabe33
Revises: 71322cd0a966
Create Date: 2026-06-06 16:29:18.254624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "021bb0fabe33"
down_revision: Union[str, Sequence[str], None] = "71322cd0a966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_read_model",
        sa.Column(
            "item_count", sa.Integer(), nullable=False, server_default="0", default=0
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_read_model", "item_count")
    # ### end Alembic commands ###
