apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: observability

data:
  promtail.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:

      - job_name: kubernetes-pods

        kubernetes_sd_configs:
          - role: pod

        relabel_configs:

          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

          - source_labels: [__meta_kubernetes_container_name]
            target_label: container

          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app

        pipeline_stages:

          # Try parse JSON logs (important for DDD / Kafka tracing)
          - json:
              expressions:
                level: level
                message: message
                service: service
                trace_id: trace_id
                correlation_id: correlation_id

          # Attach extracted fields as labels
          - labels:
              level:
              service:
              trace_id:
              correlation_id: