apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:

  name: kafka-order-service-externals-secrets

  namespace: messaging



spec:

  refreshInterval: 1m



  secretStoreRef:

    name: vault-backend

    kind: ClusterSecretStore



  target:

    name: kafka-order-service-secrets

    creationPolicy: Owner



  data:

    - secretKey: DATABASE_PASSWORD

      remoteRef:

        key: prod

        property: DATABASE_PASSWORD



    - secretKey: DOCKER_HUB_USERNAME

      remoteRef:

        key: prod

        property: DOCKER_HUB_USERNAME



    - secretKey: DOCKER_HUB_PASSWORD

      remoteRef:

        key: prod

        property: DOCKER_HUB_PASSWORD