apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
  namespace: order-service

spec:
  refreshInterval: 1m

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: dockerhub-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson

  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: prod
        property: DOCKER_CONFIG