apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-order-service-configmap
  namespace: messaging

data:
  DATABASE_HOST: "postgres.database.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: distributed
  DATABASE_USER: postgres
