name: Order Service CI - Tests

on:
  push:
  pull_request:

jobs:

  # ========================= UNIT TESTS =========================
  unit-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

    defaults:
      run:
        working-directory: order_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Run unit tests
        run: |
          pytest tests/unit_tests/


  # ========================= INTEGRATION TESTS =========================
  integration-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    defaults:
      run:
        working-directory: order_service

    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

    services:
      postgres:
        image: postgres:17

        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
          --health-start-period=10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Wait for PostgreSQL readiness
        run: |
          echo "Waiting for PostgreSQL..."

          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U $DATABASE_USER && break
            echo "DB not ready yet... attempt $i"
            sleep 2
          done

      - name: Run repository integration tests
        run: |
          pytest tests/integration/repositories/

      - name: Run service integration tests
        run: |
          pytest tests/integration/

      - name: Run API tests
        run: |
          pytest tests/api/


  # # ========================= API TESTS =========================
  api-tests:

   

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    defaults:
      run:
        working-directory: order_service

    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

    services:
      postgres:
        image: postgres:17

        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
          --health-start-period=10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary


      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Wait for PostgreSQL readiness
        run: |
          echo "Waiting for PostgreSQL..."

          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U $DATABASE_USER && break
            echo "DB not ready yet... attempt $i"
            sleep 2
          done

      - name: Run repository integration tests
        run: |
          pytest tests/integration/repositories/

      - name: Run service integration tests
        run: |
          pytest tests/integration/

      # - name: Run migrations
      #   run: |
      #     alembic upgrade head

      - name: Run API tests
        run: |
          pytest tests/api/

  
  quality-gate:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, api-tests]
    steps:
      - run: echo "All tests passed → ready to build"
  
  build:
    runs-on: ubuntu-latest
    needs: quality-gate
    permissions:
      contents: write

    steps:

      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Extract metadata (tags)
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/order-service
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest

      # 5. Build image (NO PUSH YET)
      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 6. Security scan (Trivy)
      # - name: Trivy scan
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest

      # 7. Build + Push (only if scan passed)
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Update Helm image tag
        run: |
            NEW_TAG=sha-${GITHUB_SHA::7}

            sed -i "s/tag:.*/tag: ${NEW_TAG}/" helm/order_service/values.yaml

            cat helm/order_service/values.yaml | grep tag


      - name: Commit new image tag
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

            git add helm/order_service/values.yaml

            git commit -m "Update order-service image to sha-${GITHUB_SHA::7}" || exit 0

            git push

        